apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  
spec:
  selector:
    matchLabels:
      name: httpd-frontend
      
  replicas: 3
    
  template:
     metadata: 
                
                labels: 
                 name: httpd-frontend
     spec: 
                containers:
                - name: httpd-frontend
                  image: alpine
          
