apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-nginx
  labels: 
     app: hello
     type: front-end
spec:
  template:
      
        metadata: 
         name: nginx
         labels: 
           env: nginx
        spec: 
          containers:
          - name: nginx
            image: nginx
  replicas: 3

       
